<a href="https://colab.research.google.com/github/coderanandmaurya/Feature-engineering/blob/main/Imputing_Numerical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## **Mean Median Arbitary Impute**

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [3]:
url="https://raw.githubusercontent.com/coderanandmaurya/Feature-engineering/main/titanic_toy.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df.head()

Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [6]:
df.isnull().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [7]:
mean_age = df['Age'].mean()
median_age = df['Age'].median()

In [8]:
df['Age_median'] = df['Age'].fillna(median_age)
df['Age_mean'] = df['Age'].fillna(mean_age)
df['Age_99'] = df['Age'].fillna(99)

In [9]:
df.sample(5)

Age      Fare  Family  Survived  Age_median   Age_mean  Age_99
422  29.0    7.8750       0         0        29.0  29.000000    29.0
687  19.0   10.1708       0         0        19.0  19.000000    19.0
878   NaN       NaN       0         0        28.0  29.699118    99.0
424  18.0   20.2125       2         0        18.0  18.000000    18.0
708  22.0  151.5500       0         1        22.0  22.000000    22.0

## **Using Sklearn**

In [10]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [12]:
imputer1 = SimpleImputer(strategy='median')
imputer2 = SimpleImputer(strategy='mean')
#imputer3 = SimpleImputer(strategy='constant',fill_value=99)

In [13]:
trf = ColumnTransformer([
    ('imputer1',imputer1,['Age']),
    ('imputer2',imputer2,['Fare']),#('imputer3',imputer3,['Age']),
],remainder='passthrough')

In [14]:
trf.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer1', SimpleImputer(strategy='median'),
                                 ['Age']),
                                ('imputer2', SimpleImputer(), ['Fare'])])

In [15]:
trf.named_transformers_['imputer1'].statistics_

array([28.75])

In [16]:
trf.named_transformers_['imputer2'].statistics_

array([32.61759689])

In [17]:
X_train = trf.transform(X_train)
X_test = trf.transform(X_test)

In [18]:
X_train

array([[ 40.        ,  27.7208    ,   0.        ,  40.        ,
         40.        ,  40.        ],
       [  4.        ,  16.7       ,   2.        ,   4.        ,
          4.        ,   4.        ],
       [ 47.        ,   9.        ,   0.        ,  47.        ,
         47.        ,  47.        ],
       ...,
       [ 71.        ,  49.5042    ,   0.        ,  71.        ,
         71.        ,  71.        ],
       [ 28.75      , 221.7792    ,   0.        ,  28.        ,
         29.69911765,  99.        ],
       [ 28.75      ,  25.925     ,   0.        ,  28.        ,
         29.69911765,  99.        ]])